### ISSUE TITLE
Loan Types filter

### ISSUE THREAD

**Issue by VictorFatoux** [thicccat688/peerberrypy#8]
`Exception has occurred: TypeError
'int' object is not iterable
  File "\peerberrypy\api.py", line 211, in get_loans
    for idx, type_ in enumerate(loan_types):
  File "main.py", line 20, in <module>
    pd = api_client.get_loans(quantity=100, min_interest_rate= 9, loan_types=1)
TypeError: 'int' object is not iterable`
Hello, I think there's a little problem with the loan type filter, can you check if it works for you ? thanks.

**Comment by thicccat688** [comment]
Update: I've looked in to it and turns out I was wrong. I've fixed the filter for the loans and added more validations to the function arguments. I'm going to re-test all the filters to see if I can catch any bugs. 

Just do the usual:
python -m pip install --upgrade peerberrypy

And try:
api_client.get_loans(quantity=100, min_interest_rate=9, loan_types=['short_term'])

And you'll get your desired result!
